### ISSUE TITLE
drachtio server crash

### ISSUE THREAD

**Issue by ErhanOnur** [drachtio/drachtio-server#330]
Hi,

Our drachtio server is crashed. I checked the coredump file. it gave me following result. Could you please comment on this issue?
Version is : v0.8.24
Thank you

f4-ae06-48acce1c3913.502102.294283128
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/bin/drachtio...
[New LWP 502102]
[New LWP 502103]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/local/bin/drachtio -l debug -f /etc/drachtio.conf.ws.xml --daemon'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fa1012e3980 (LWP 502102))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fa101fc2859 in __GI_abort () at abort.c:79
#2  0x00007fa10202d26e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fa102157298 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007fa1020352fc in malloc_printerr (str=str@entry=0x7fa102159248 "corrupted double-linked list (not small)") at malloc.c:5347
#4  0x00007fa102035977 in unlink_chunk (p=p@entry=0x564588ade970, av=0x7fa10218cb80 <main_arena>) at malloc.c:1468
#5  0x00007fa1020385f3 in _int_malloc (av=av@entry=0x7fa10218cb80 <main_arena>, bytes=bytes@entry=65536) at malloc.c:4041
#6  0x00007fa10203a299 in __GI___libc_malloc (bytes=65536) at malloc.c:3066
#7  0x0000564586f73712 in ws_init ()
#8  0x0000564586f7136e in tport_ws_init_secondary ()
#9  0x0000564586f56373 in tport_alloc_secondary ()
#10 0x0000564586f5d1ea in tport_accept ()
#11 0x0000564586f5db2e in tport_wakeup_pri ()
#12 0x0000564586f9b6a5 in su_epoll_port_wait_events ()
#13 0x0000564586f9a1c4 in su_base_port_run ()
#14 0x0000564586f470ec in su_port_run ()
#15 0x0000564586f482b4 in su_root_run ()
#16 0x0000564586dda947 in drachtio::DrachtioController::run (this=0x56458898c140) at ../src/controller.cpp:1380
#17 0x0000564586db41e0 in main (argc=6, argv=0x7ffcd1efd528) at ../src/main.cpp:47

**Comment by davehorton** [comment]
can you provide the drachtio log file leading up to the crash?  What version/tag are you running?
